--- #YAML:1.0
name: Javascript-SHA1
version: 1.01
author:
  - Ron Savage <ron@savage.net.au>
abstract: Calculate the SHA1 digest of a CGI form field
license: artistic
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
